apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: software-env-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    helm:
      version: v3
    repoURL: https://github.com/andrepinto/dd-releases
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

